server:
  port: 8081

logging:
  level:
    root: DEBUG
    com.company: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method


spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000  # 24 hours in milliseconds


email:
  mailgun:
    url: https://api.mailgun.net/v3/sandbox4cbbd7296e6c4d0b9df247d02c5cfebe.mailgun.org
    api-key: ${MAILGUN_API_KEY}
    from: Mailgun Sandbox <postmaster@sandbox4cbbd7296e6c4d0b9df247d02c5cfebe.mailgun.org>